ASSUME  CS:CODE, DS:DATA
DATA    SEGMENT
        STRING DB 50H,20H,60H,45H
        COUNT EQU 03H
        LARGEST DB 01H DUP(?)
DATA    ENDS
CODE    SEGMENT
START:  MOV AX, DATA
        MOV DS, AX
 	LEA SI, STRING
	MOV CL, COUNT
	MOV AL, [SI]
AGAIN:  CMP AL, [SI+1]
        JC NEXT
	MOV AL, [SI+1]
NEXT:	INC SI
	DEC CL
	JNZ AGAIN
        LEA SI, LARGEST
	MOV [SI], AL
        MOV AL,0H
	MOV AH,04CH
	INT 21H
CODE ENDS
END START
         